- mail.class.php
Smart å glemme å switche branch #notetoself
> Oppdatert mail-class for å støtte custom sendFrom

- write_monstring.class.php
> Cherry-pick f86a8385

- mail.class.php
@mariusmandal Fant ut at det er gjort oppdateringer i mail.class.php på serveren, men ikke i UKMapi. Har lagt de inn her.
> Mailer update

- venner.class.php
> Lagt til venner.class.php

- Innslag/Samling.php
Ikke funnet noenting som krasjer av denne deprecation (etter merge UKMNorge/UKMdelta#311), men du vet kanskje om noen steder den blir brukt?
> Deprecate load av delta-brukere via b_password.

- Innslag/Samling.php
Håper jeg - ikke fått fremprovosert i .dev.
> Fix UKMNorge/UKMdelta#315

- Wordpress/Blog.php
Required før du merger UKMNorge\UKMusers#11
> Funksjoner for å jobbe på hovedblogg i Wordpress\Blog.

- Filmer/UKMTV/Film.php
- Filmer/UKMTV/Filmer.php
- Filmer/UKMTV/Server/BandwidthMode.php
- Filmer/UKMTV/Server/Cache.php
- Filmer/UKMTV/Server/Caches.php
- Filmer/UKMTV/Server/Server.php
- Kommunikasjon/Epost.php
- Meta/Collection.php
- Meta/Write.php
- README.md
- _DB-migration/2020-03-25-tvconf.sql
> Spring clean 2020, runde 2

- Arrangement/Arrangement.php
- Arrangement/Arrangementer.php
- Arrangement/Filter.php
- Arrangement/Kommende.php
- Arrangement/Kontaktperson/Kontaktperson.php
- Arrangement/Kontaktperson/Write.php
- Arrangement/Load.php
- Arrangement/Tidligere.php
- Arrangement/Write.php
- Innslag/Personer/Personer.php
- Innslag/Samling.php
- Nettverk/Administrator.php
- Nettverk/Administratorer.php
- Nettverk/Omrade.php
- Nettverk/Proxy/Kontaktperson.php
- Nettverk/WriteAdministrator.php
- Nettverk/WriteOmrade.php
- Wordpress/Blog.php
- _DB-migration/2020-09-24-nettverk_admins.sql
Håndterer arrangementer og påmeldinger uten å vite hvilken sesong vi er i nå
> Feature seasonfree

- Arrangement/Arrangement.php
- Arrangement/Write.php
- _DB-migration/2021-02-06-smartukm_place.sql
> Støtte for egne videresendingsfrister

- Wordpress/Modul.php
Dette kan påvirke alle UKM plugins.
> Ny implementasjon av getPluginUrl()

- Nettverk/WriteOmrade.php
Close https://github.com/UKMNorge/UKMnettverket/issues/56
Close https://github.com/UKMNorge/UKMapi/issues/57
Utviklingstid: 3 timer.
> Legg til admin i alle arrangementer i fylke

- Arrangement/Kontaktperson/Kontaktperson.php
- Arrangement/Kontaktperson/Write.php
- Innslag/Innslag.php
- Innslag/Personer/Person.php
- Innslag/Personer/Write.php
- Innslag/Write.php
- Tools/Sanitizer.php
Close #141.
Utviklingstid: 5 timer.
Notat: Det har vært litt frem o tilbake med researching og for denne løsningen ble det ikke gjort grundig testing om fjerning av alle emoji-tegn. Det ser ut som det fungerer med de fleste emoji-tegn.
> Rense: fjerner emoji fra navn og etternavn

- Arrangement/UKMFestival.php
- UKMFestivalen/Overnatting/OvernattingGruppe.php
- UKMFestivalen/Overnatting/OvernattingPerson.php
- UKMFestivalen/Overnatting/OvernattingRom.php
- UKMFestivalen/Overnatting/Samling.php
* UKMFestivalen klasse som representerer UKM Nasjonal Festivalen og utvider Arrangement
* UKM Festivalen overnatting funksjoner
> Ukm festivalen arv

- Arrangement/Videresending/Ledere/Hovedleder.php
- Arrangement/Videresending/Ledere/Leder.php
- Arrangement/Videresending/Ledere/Write.php
Implementasjon av ny type "leder" som heter sykerom og som brukes for å ha et rom i hotellet for bestemte netter.
Nye metoder for å utføre rapporter for ledere og overnatting på UKM Festivalen
> Sykerom og overnating-ledere

- Nettverk/Proxy/Kontaktperson.php
- Wordpress/User.php
- Wordpress/WriteUser.php
User får bilde fra en tabell som hetet `wp_user_bilde`.
Koden for å opprette databasen:
```SQL
CREATE TABLE wp_user_bilde (
id int NOT NULL AUTO_INCREMENT,
wp_user int NOT NULL,
bilde_url varchar(255),
PRIMARY KEY (id)
);
```
> Admin bilder

- Filmer/UKMTV/CloudflareFilm.php
- Filmer/UKMTV/Filmer.php
- Filmer/UKMTV/Write.php
- Filmer/UKMTV/WriteFilmCloudflare.php
Integrasjon av Cloudflare Stream på UKM API systemet. Inneholder modifikasjoner på Filmer som brukes mest på UKMTV.
> Cloudflare ukmtv

- Arrangement/Arrangement.php
- Arrangement/UKMFestival.php
- Arrangement/Videresending/Request/RequestVideresending.php
- Arrangement/Videresending/Request/RequestVideresendinger.php
- Arrangement/Videresending/Request/Write.php
Brukere kan sende forespørsel om å opne videresending. Akkurat nå fungerer det kun på arrangement av type land (UKM-festivalen)
> Request videresending

- Geografi/Kommune.php
Noen kommuner ønsker å ha felles kommuneside derfor ble det gjort endringer på Kommune klasse for å håndtere det. Det brukes ny tabell i SS3 database for å oppnå det.
```mysql
CREATE TABLE ukm_kommune_path (
id int NOT NULL AUTO_INCREMENT,
kommune_id int NOT NULL,
path TEXT,
PRIMARY KEY (id)
);
```
> Endringer på Kommune angående felles kommuneside

- Geografi/Fylker.php
> Fylkesinndeling2024

- Arrangement/Arrangement.php
- Arrangement/Program/Hendelser.php
- Arrangement/Skjema/Respondenter.php
- Arrangement/Videresending/Videresending.php
- Arrangement/Write.php
- Database/SQL/Delete.php
- Database/SQL/Insert.php
- Database/SQL/Query.php
- Filmer/UKMTV/Tags/Tags.php
- Geografi/Kommune.php
- Innslag/Samling.php
- Slack/API/OLD_Response/Action.php
- Slack/API/OLD_Response/Attachment.php
- Slack/API/OLD_Response/Response.php
- composer.json
- composer.lock
- mail/class.phpmailer.php
Gjort store endringer i koden for å fikse feil som kommer når koden kjøres på PHP 8.2. I tillegg er det oppdater composer.lock fila for å hente pakker som støtter PHP 8.
> Tilpasning til PHP 8

- Statistikk/Objekter/StatistikkArrangement.php
- Statistikk/Objekter/StatistikkFylke.php
- Statistikk/Objekter/StatistikkKommune.php
- Statistikk/Objekter/StatistikkSuper.php
Implementering av statistikk modul
> Statistikk modul

- Arrangement/Kontaktperson/Samling.php
- Arrangement/Write.php
- Nettverk/Omrade.php
- Nettverk/OmradeKontaktperson.php
- Nettverk/OmradeKontaktpersoner.php
- Nettverk/WriteOmrade.php
- Nettverk/WriteOmradeKontaktperson.php
- OAuth2/ArrSys/AccessControlArrSys.php
Implementering av Omradekontaktperson
> Omraade kontaktpersoner

- Statistikk/Objekter/StatistikkNasjonalt.php
> Added function for unregistered users
